from src.application.docs.auth_docs import AUTH_LOGIN_DOC
from src.application.docs.consultas_docs import CONSULTA_CADASTRAR_DOC, CONSULTA_LISTAR_DOC
from src.application.docs.usuarios_docs import USUARIO_CADASTRAR_DOC, USUARIO_CADASTRAR_ADMIN_DOC, USUARIO_CADASTRAR_MEDICO_DOC